Repository googleapis/java-vision, pull requests merged in 2020-10, with the labels that each got.

#251 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: api: vision, cla: yes, context: full

#253 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#261 ci(java): suggest formatting fixes
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#269 build: assign samples pull requests via blunderbuss
  .github/blunderbuss.yml
Labels: api: vision, cla: yes, samples

#265 chore: regenerate common templates
  .github/workflows/approve-readme.yaml
  .kokoro/build.sh
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#268 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#278 build: fix blunderbuss team config
  .github/blunderbuss.yml
Labels: api: vision, cla: yes

#279 chore: regenerate common templates
  .github/snippet-bot.yml
  renovate.json
  synth.metadata
Labels: api: vision, cla: yes, context: full

#280 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#282 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#285 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#283 chore: regenerate common templates
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#290 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#295 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#296 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#298 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
