Repository googleapis/java-vision, pull requests merged in 2020-08, with the labels that each got.

#196 cleanup: removes unused kokoro config files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#198 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#193 samples: migrate samples from GoogleCloudPlatform/java-docs-samples /vision/beta/cloud-client
  samples/install-without-bom/resources/gcp-logos.png
  samples/install-without-bom/resources/handwritten.jpg
  samples/snapshot/resources/gcp-logos.png
  samples/snapshot/resources/handwritten.jpg
  samples/snippets/resources/gcp-logos.png
  samples/snippets/resources/handwritten.jpg
  samples/snippets/src/main/java/com/example/vision/AsyncBatchAnnotateImagesGcs.java
  samples/snippets/src/main/java/com/example/vision/DetectBatchAnnotateFiles.java
  samples/snippets/src/main/java/com/example/vision/DetectBatchAnnotateFilesGcs.java
  samples/snippets/src/main/java/com/example/vision/DetectBeta.java
  samples/snippets/src/test/java/com/example/vision/DetectBetaIT.java
Labels: cla: yes

#208 chore: regenerate samples list
  README.md
  synth.metadata
Labels: cla: yes, context: none

#209 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#210 tests: switching assertTrue with assertThat to get better output on w…
  google-cloud-vision/pom.xml
  google-cloud-vision/src/test/java/com/google/cloud/vision/it/ITSystemTest.java
Labels: cla: yes

#214 test: fixed flaky test on detectLandMarks using URL
  google-cloud-vision/src/test/java/com/google/cloud/vision/it/ITSystemTest.java
Labels: cla: yes
