Repository googleapis/java-vision, pull requests merged in 2020-11, with the labels that each got.

#291 chore: moving the rest of the vision samples
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/src/test/java/com/example/vision/AsyncBatchAnnotateImagesTest.java
  samples/snippets/src/test/java/com/example/vision/BatchAnnotateFilesGcsTest.java
  samples/snippets/src/test/java/com/example/vision/BatchAnnotateFilesTest.java
  samples/snippets/src/test/java/com/example/vision/DetectBetaIT.java
  samples/snippets/src/test/java/com/example/vision/DetectCropHintsGcsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectCropHintsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectFacesGcsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectFacesTest.java
  samples/snippets/src/test/java/com/example/vision/DetectIT.java
  samples/snippets/src/test/java/com/example/vision/DetectLabelsGcsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectLabelsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectLandmarksGcsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectLandmarksTest.java
  samples/snippets/src/test/java/com/example/vision/DetectLogosGcsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectLogosTest.java
  samples/snippets/src/test/java/com/example/vision/DetectPropertiesGcsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectPropertiesTest.java
  samples/snippets/src/test/java/com/example/vision/DetectSafeSearchGcsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectSafeSearchTest.java
  samples/snippets/src/test/java/com/example/vision/DetectTextGcsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectTextTest.java
  samples/snippets/src/test/java/com/example/vision/DetectWebDetectionsGcsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectWebDetectionsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectWebEntitiesGcsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectWebEntitiesIncludeGeoResultsGcsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectWebEntitiesIncludeGeoResultsTest.java
  samples/snippets/src/test/java/com/example/vision/DetectWebEntitiesTest.java
  samples/snippets/src/test/java/com/example/vision/ImportProductSetsIT.java
  samples/snippets/src/test/java/com/example/vision/ProductInProductSetManagementIT.java
  samples/snippets/src/test/java/com/example/vision/ProductManagementIT.java
  samples/snippets/src/test/java/com/example/vision/ProductSearchIT.java
  samples/snippets/src/test/java/com/example/vision/ProductSetManagementIT.java
  samples/snippets/src/test/java/com/example/vision/ReferenceImageManagementIT.java
  samples/snippets/src/test/java/com/example/vision/SetEndpointIT.java
  samples/snippets/src/test/java/vision/snippets/ProductInProductSetManagementTests.java
  samples/snippets/src/test/java/vision/snippets/ProductManagementTests.java
  samples/spring-framework/README.md
  samples/spring-framework/pom.xml
  samples/spring-framework/src/main/java/com/example/vision/Application.java
  samples/spring-framework/src/main/java/com/example/vision/VisionController.java
  samples/spring-framework/src/main/resources/static/index.html
  samples/spring-framework/src/main/resources/templates/result.html
Labels: api: vision, cla: yes, samples

#302 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#303 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#275 test: fixed the flaky test
  google-cloud-vision/src/test/java/com/google/cloud/vision/it/ITSystemTest.java
Labels: api: vision, cla: yes

#306 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#308 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#309 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#311 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#314 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#321 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#328 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#325 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#329 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#330 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#331 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#333 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full, samples
