Repository googleapis/java-vision, pull requests merged in 2020-06, with the labels that each got.

#140 fix: restore GAPIC v2 retry configs
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/stub/ImageAnnotatorStubSettings.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#154 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#158 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#163 ci: switch to secret manager for sample/integration tests
  .github/CODEOWNERS
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  CONTRIBUTING.md
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#172 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-vision/pom.xml
  grpc-google-cloud-vision-v1/pom.xml
  grpc-google-cloud-vision-v1p1beta1/pom.xml
  grpc-google-cloud-vision-v1p2beta1/pom.xml
  grpc-google-cloud-vision-v1p3beta1/pom.xml
  grpc-google-cloud-vision-v1p4beta1/pom.xml
  pom.xml
  proto-google-cloud-vision-v1/pom.xml
  proto-google-cloud-vision-v1p1beta1/pom.xml
  proto-google-cloud-vision-v1p2beta1/pom.xml
  proto-google-cloud-vision-v1p3beta1/pom.xml
  proto-google-cloud-vision-v1p4beta1/pom.xml
Labels: cla: yes

#171 fix: migrate retry settings to grpc_service_config
  README.md
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/ImageAnnotatorClient.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/ImageAnnotatorSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/ProductSearchClient.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/ProductSearchSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/package-info.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/GrpcImageAnnotatorStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/GrpcProductSearchStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/ImageAnnotatorStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/ImageAnnotatorStubSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/ProductSearchStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/ProductSearchStubSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p1beta1/stub/ImageAnnotatorStubSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p2beta1/ImageAnnotatorClient.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p2beta1/ImageAnnotatorSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p2beta1/stub/GrpcImageAnnotatorStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p2beta1/stub/ImageAnnotatorStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p2beta1/stub/ImageAnnotatorStubSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/ProductSearchClient.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/ProductSearchSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/package-info.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/stub/GrpcProductSearchStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/stub/ImageAnnotatorStubSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/stub/ProductSearchStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/stub/ProductSearchStubSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/ImageAnnotatorClient.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/ImageAnnotatorSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/ProductSearchClient.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/ProductSearchSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/package-info.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/stub/GrpcImageAnnotatorStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/stub/GrpcProductSearchStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/stub/ImageAnnotatorStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/stub/ImageAnnotatorStubSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/stub/ProductSearchStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/stub/ProductSearchStubSettings.java
  google-cloud-vision/src/test/java/com/google/cloud/vision/v1/ImageAnnotatorClientTest.java
  google-cloud-vision/src/test/java/com/google/cloud/vision/v1/ProductSearchClientTest.java
  google-cloud-vision/src/test/java/com/google/cloud/vision/v1p2beta1/ImageAnnotatorClientTest.java
  google-cloud-vision/src/test/java/com/google/cloud/vision/v1p3beta1/ProductSearchClientTest.java
  google-cloud-vision/src/test/java/com/google/cloud/vision/v1p4beta1/ImageAnnotatorClientTest.java
  google-cloud-vision/src/test/java/com/google/cloud/vision/v1p4beta1/ProductSearchClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#181 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
