Repository googleapis/java-vision, pull requests merged in 2020-07, with the labels that each got.

#182 ci(java): run dependency test on Java 8 and 11
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  pom.xml
  synth.metadata
Labels: automerge, cla: yes, context: full

#186 build: remove unnecessary objenesis ignore rule
  pom.xml
Labels: cla: yes

#191 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#192 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
