Repository googleapis/java-vision, pull requests merged in 2021-04, with the labels that each got.

#458 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#460 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#462 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#464 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#468 fix: typo
  .kokoro/build.sh
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#473 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#476 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#477 test (samples): service throttles on public URLs & its known issue
  samples/snippets/src/test/java/com/example/vision/DetectLandmarksGcsTest.java
Labels: api: vision, cla: yes, samples

#488 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#489 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes
