Repository googleapis/java-vision, pull requests merged in 2021-02, with the labels that each got.

#377 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#390 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/auto-release.yaml
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  LICENSE
  synth.metadata
Labels: api: vision, cla: yes, context: partial

#393 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#391 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#396 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#394 feat: add LEFT_CHEEK_CENTER and RIGHT_CHEEK_CENTER FaceAnnotation Landmark Types
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/ImageAnnotatorClient.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/ProductSearchClient.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/package-info.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p1beta1/ImageAnnotatorClient.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p1beta1/package-info.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p2beta1/ImageAnnotatorClient.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p2beta1/package-info.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/ImageAnnotatorClient.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/ProductSearchClient.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/package-info.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/ImageAnnotatorClient.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/ProductSearchClient.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/package-info.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/BatchAnnotateFilesRequest.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/BatchAnnotateFilesRequestOrBuilder.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/FaceAnnotation.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/GetProductSetRequest.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/GetProductSetRequestOrBuilder.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/Image.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ImageAnnotatorProto.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ImageOrBuilder.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/Product.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductOrBuilder.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchParams.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchParamsOrBuilder.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/ProductSearchProto.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/SafeSearchAnnotation.java
  proto-google-cloud-vision-v1/src/main/java/com/google/cloud/vision/v1/SafeSearchAnnotationOrBuilder.java
  proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/geometry.proto
  proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/image_annotator.proto
  proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/product_search.proto
  proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/product_search_service.proto
  proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/text_annotation.proto
  proto-google-cloud-vision-v1/src/main/proto/google/cloud/vision/v1/web_detection.proto
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#399 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#398 chore: update gapic-generator-java to 0.0.20
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/GrpcImageAnnotatorStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/GrpcProductSearchStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p1beta1/stub/GrpcImageAnnotatorStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p2beta1/stub/GrpcImageAnnotatorStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/stub/GrpcImageAnnotatorStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/stub/GrpcProductSearchStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/stub/GrpcImageAnnotatorStub.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/stub/GrpcProductSearchStub.java
  google-cloud-vision/src/test/java/com/google/cloud/vision/v1/MockImageAnnotatorImpl.java
  google-cloud-vision/src/test/java/com/google/cloud/vision/v1/MockProductSearchImpl.java
  google-cloud-vision/src/test/java/com/google/cloud/vision/v1p1beta1/MockImageAnnotatorImpl.java
  google-cloud-vision/src/test/java/com/google/cloud/vision/v1p2beta1/MockImageAnnotatorImpl.java
  google-cloud-vision/src/test/java/com/google/cloud/vision/v1p3beta1/MockImageAnnotatorImpl.java
  google-cloud-vision/src/test/java/com/google/cloud/vision/v1p3beta1/MockProductSearchImpl.java
  google-cloud-vision/src/test/java/com/google/cloud/vision/v1p4beta1/MockImageAnnotatorImpl.java
  google-cloud-vision/src/test/java/com/google/cloud/vision/v1p4beta1/MockProductSearchImpl.java
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#400 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#401 chore: update javadoc config link
  pom.xml
Labels: api: vision, cla: yes

#403 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#404 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#392 test(samples): prevent failure in nightly run by adding retry
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/test/java/com/example/vision/DetectIT.java
Labels: api: vision, automerge, cla: yes

#407 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/gapic_metadata.json
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p1beta1/gapic_metadata.json
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p2beta1/gapic_metadata.json
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/gapic_metadata.json
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/gapic_metadata.json
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#410 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#412 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#413 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#415 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes
