Repository googleapis/java-vision, pull requests merged in 2021-05, with the labels that each got.

#492 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: vision, automerge, cla: yes

#491 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: none

#499 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#501 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#503 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#505 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#510 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#511 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#513 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#521 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#522 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#517 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#523 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes
