Repository googleapis/java-vision, pull requests merged in 2021-07, with the labels that each got.

#560 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#571 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#572 chore: remove distributionManagement section
  pom.xml
Labels: api: vision, automerge, cla: yes

#573 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#574 chore: remove distributionManagement section
  google-cloud-vision-bom/pom.xml
Labels: api: vision, automerge, cla: yes

#577 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#576 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: vision, automerge, cla: yes, context: full

#579 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#580 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#583 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#589 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#590 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: vision, automerge, cla: yes

#592 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: vision, automerge, cla: yes

#593 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: api: vision, automerge, cla: yes
