Repository googleapis/java-vision, pull requests merged in 2021-09, with the labels that each got.

#621 chore: update gapic-generator-java version to 2.1.0
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/ImageAnnotatorStubSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1/stub/ProductSearchStubSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p1beta1/stub/ImageAnnotatorStubSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p2beta1/stub/ImageAnnotatorStubSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/stub/ImageAnnotatorStubSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p3beta1/stub/ProductSearchStubSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/stub/ImageAnnotatorStubSettings.java
  google-cloud-vision/src/main/java/com/google/cloud/vision/v1p4beta1/stub/ProductSearchStubSettings.java
  synth.metadata
Labels: cla: yes, api: vision, automerge, context: full

#659 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, api: vision, automerge, context: full

#661 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: vision, automerge, context: full

#663 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  README.md
  google-cloud-vision-bom/pom.xml
  google-cloud-vision/pom.xml
  owlbot.py
  pom.xml
  samples/generated/src/main/java/com/google/cloud/examples/vision/v1/VisionAsyncBatchAnnotateImages.java
  samples/generated/src/main/java/com/google/cloud/examples/vision/v1/VisionBatchAnnotateFiles.java
  samples/generated/src/main/java/com/google/cloud/examples/vision/v1/VisionBatchAnnotateFilesGcs.java
  samples/snippets/src/main/java/com/example/vision/DetectBeta.java
  samples/snippets/src/main/java/com/example/vision/ImportProductSets.java
  samples/snippets/src/test/java/com/example/vision/DetectBetaIT.java
  samples/snippets/src/test/java/com/example/vision/DetectIT.java
  samples/snippets/src/test/java/com/example/vision/DetectLandmarksGcsTest.java
  samples/spring-framework/src/main/java/com/example/vision/VisionController.java
  versions.txt
Labels: cla: yes, api: vision

#671 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: vision, automerge

#669 chore(java): update windows build
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: vision, context: full

#690 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: vision, automerge

#700 chore: update owlbot-java image digest
  .github/.OwlBot.lock.yaml
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  README.md
Labels: cla: yes, api: vision, automerge

#699 chore: make owlbot check required
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: vision, automerge

#704 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: vision, automerge

#714 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: vision, automerge
